#!/usr/bin/bash
#
#   repo-add - a wrapper for running the real repo-add in the source tree
#
#   Copyright (c) 2013-2019 Pacman Development Team <pacman-dev@archlinux.org>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

DIR="/home/charlie/repos/pacman-5.2.1/pacman-5.2.1/pacman-5.2.1/_build/sub/scripts"

LIBRARY="$DIR"/libmakepkg exec bash -$- "$DIR"/.lib/repo-add "$@"
